### ISSUE TITLE
Sink lacks restrictedToMinimumLevel configuration parameter

### ISSUE THREAD

**Issue by lukedreamwalker** [IonxSolutions/serilog-sinks-syslog#1]
The configuration parameter restrictedToMinimumLevel ist not implemented at the moment.
Are there any plans for this?

**Comment by colin-anderson** [comment]
Happy to take a PR for this if you want to have a crack at it?

**Comment by colin-anderson** [comment]
Resolved by #2

NuGet package will probably be bumped later today
