### ISSUE TITLE
Configure batchSettings via IConfiguration

### ISSUE THREAD

**Issue by cw-andrews** [IonxSolutions/serilog-sinks-syslog#11]
I believe that I need to use this package as the other Serilog Syslog package only does UDP. However, I also need to configure it via JSON configuration files. 

Do you know if this will this work (.NET Core, IConfiguration)?
```
{
	"Name": "TcpSyslog",
	"Args": {
		"server": "logsX.papertrailapp.com",
		"port": "XXXXX",
		"application": "MyApp",
		"facility": "Local7",
		"format": "RFC5424",
		"outputTemplate": "{Message} {NewLine}{Exception}",
		"batchSettings": {
			"BatchSizeLimit": 1000,
			"Period": "0.00:00:01",
			"QueueLimit": "100_000"
		}
	}
}
```

If not, is there another way?

Thanks!

**Comment by colin-anderson** [comment]
There are [2 extension methods](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/master/src/Serilog.Sinks.Syslog/SyslogLoggerConfigurationExtensions.cs) for configuring from JSON, so you'd need to make sure your JSON key names matched the parameter names. A simple example would be something like:

```json
{
  "Name": "TcpSyslog",
  "Args": {
    "host": "logsX.papertrailapp.com",
    "port": 123,
    "appName": "MyApp",
    "facility": "Local7",
    "format": "RFC5424",
    "outputTemplate": "{Message} {NewLine}{Exception}"
  }
}
```

Looking again at the extension methods, it seems we don't actually have one that supports setting the above *and* the batch settings - it's either or. I think that's something we should fix.

As configuring from JSON is so common, we should also provide another simple sample app that illustrates how to do this.

**Comment by cw-andrews** [comment]
@colin-anderson Thanks for getting back to me so quickly. 
Do you accept pull requests? Is your normal process to actually create some sort of milestone for it, or what?

**Comment by colin-anderson** [comment]
Would gladly take a pull request!

Yes, that's one of the extension methods (they have an insane number of parameters, but that's what allows JSON/XML config to work!). What we'd need is a new extension method modelled on that one, which takes more parameters to configure a `PeriodicBatchingSinkOptions` instance.
