### ISSUE TITLE
Expose SslStream.AuthenticateAsClient's CheckCertificateRevocation Parameter

### ISSUE THREAD

**Issue by Kevin-Andrew** [IonxSolutions/serilog-sinks-syslog#14]
Currently in the `SyslogTcpSink.cs`, the `GetStream(Stream baseStream)` method will make a call to the [`sslStream.AuthenticateAsClientAsync()` method as follows](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/master/src/Serilog.Sinks.Syslog/Sinks/SyslogTcpSink.cs#L151):

```
await sslStream.AuthenticateAsClientAsync(this.Host, this.clientCert,
                this.secureProtocols, false).ConfigureAwait(false);
```

The last parameter is hard coded to `false` (not the part in the `ConfigureAwait`). There are some use cases where this may need to be configurable. For example, it is a requirement for [Common Criteria Certification](https://www.blancco.com/blog-what-is-common-criteria-certification-why-is-it-important/) for secure connections to check for revoked certificates in CRLs.

Would it be possible to expose this as an additional configuration setting on the `SyslogTcpConfig` class named `CheckCertificateRevocation`, with the default being `false`, which should preserve backwards compatibility.

**Comment by colin-anderson** [comment]
Agree this needs to be configurable - thanks for the PR too 😃
