### ISSUE TITLE
Call to AuthenticateAsClientAsync() Hangs When Server Doesn't Support TLS

### ISSUE THREAD

**Issue by Kevin-Andrew** [IonxSolutions/serilog-sinks-syslog#18]
Asynchronous calls do not have a default timeout period like most of their synchronous counterparts do. The [call to the AuthenticateAsClientAsync() method](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/v2.0.0/src/Serilog.Sinks.Syslog/Sinks/SyslogTcpSink.cs#L150) initiates the TLS handshake, which requires sending AND receiving data from the server. If the server is just a plain socket listener that doesn't have TLS enabled, then it's possible that this method call will wait forever. For example, if you run the [Syslog Watcher](https://ezfive.com/syslog-watcher/downloads/) server program on Windows, it does not support TLS. However, it will gladly accept the TCP connection and the TLS handshake data and not send anything in response. Therefore, this method will wait forever, giving no indication that anything is wrong. Implementing a timeout that will interrupt the async `await` is needed in order to provide useful feedback.

Note that [with the .NET 5.0 version of this method](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclientasync?view=net-5.0#System_Net_Security_SslStream_AuthenticateAsClientAsync_System_Net_Security_SslClientAuthenticationOptions_System_Threading_CancellationToken_) and[ .NET Core 2.1+ of this method](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclientasync?view=netcore-2.1#System_Net_Security_SslStream_AuthenticateAsClientAsync_System_Net_Security_SslClientAuthenticationOptions_System_Threading_CancellationToken_), a cancellation token can be passed directly in as a parameter. But we are not targeting either of those frameworks.

In the screen shot below, using the [Syslog Watcher](https://ezfive.com/syslog-watcher/downloads/) program, we can configure it to listen on TCP, but it does not support TLS. When the client makes a call to the SslStream.AuthenticateAsClientAsync() method, we see that the server receives TLS handshake data, but doesn't respond. Therefore, because the call is async, it will wait forever.
![image](https://user-images.githubusercontent.com/22459191/108022837-93524f80-6fde-11eb-9d8b-c70a1471708d.png)

**Comment by colin-anderson** [comment]
Another great catch, thanks for the report!
