### ISSUE TITLE
Unit Test Set to Wait for 6,000 Seconds?

### ISSUE THREAD

**Issue by Kevin-Andrew** [IonxSolutions/serilog-sinks-syslog#20]
The `AsyncCountdownEvent` [class's `WaitAsync()` method](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/v2.0.0/test/Serilog.Sinks.Syslog.Tests/Support/AsyncCountdownEvent.cs#L23) takes in an integer representing the number of seconds to wait. That is used in a few places in the Unit Tests, like [here](https://github.com/IonxSolutions/serilog-sinks-syslog/blob/v2.0.0/test/Serilog.Sinks.Syslog.Tests/TcpSyslogSinkTests.cs#L63), with 6,000 as the timeout value. Is that really the intent?

```
public Task WaitAsync(int timeout, CancellationToken ct)
{
    return WaitAsync(TimeSpan.FromSeconds(timeout), ct);
}
```
```
// Wait until the server has received all the messages we sent, or the timeout expires
await this.countdown.WaitAsync(6000, this.cts.Token);
```

**Comment by colin-anderson** [comment]
I think someone (*cough*) must have set it high while debugging a test, and forgotten to set it back again.

I'll fix this when I cut the next release that includes your latest PR, #19.
