### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by colin-anderson** [IonxSolutions/serilog-sinks-syslog#23]
Instead of using both Travis and AppVeyor (because we need to run tests on both Linux & Windows), switch to `https://github.com/features/`.

This will give us less to maintain, and anyway, Travis has made it clear they don't want to support OSS projects anymore, and queue times for both AppVeyor and Travis can be really high sometimes.

**Comment by Kevin-Andrew** [comment]
As mentioned in PR #63, moving to GitHub Actions has the caveat of not supporting .NET Framework 4.6.2. A GitHub Windows Server 2019 "runner" doesn't have .NET Framework 4.6.2 installed on it. See https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#net-core-tools

It only has .NET Framework 4.7.2 and 4.8, as well as .NET Core 6. They deprecated .NET Core 3.1 as well.

Compared to what AppVeyor offers on their Windows Server 2019 build machine:
https://www.appveyor.com/docs/windows-images-software/#net-framework

So if switching to GitHub Actions, we'd have to reduce the build targets down to just .NET Framework 4.7.2 and .NET 6.

However, that was deemed not acceptable, [stating that .NET Framework 4.6.2 support must remain](https://github.com/IonxSolutions/serilog-sinks-syslog/pull/63#issuecomment-1625162749):
> We're going to need to keep .NET Framework 4.6.2 tho

**Comment by colin-anderson** [comment]
Cancelled (for a while anyway), due to GitHub Actions not supporting .NET Framework 4.6.2.

**Comment by Kevin-Andrew** [comment]
Just a thought I had and wanted to make note of it for if/when we ever come back to this.

I would suppose that there should be nothing stopping us from having some kind of pre-build event that installs the .NET Framework 4.6.2 SDK on the GitHub build server/runner, prior to doing the actual build. Hopefully it wouldn't require a reboot.

The SDK installer can be downloaded from:
https://dotnet.microsoft.com/en-us/download/visual-studio-sdks

Or there is a PowerShell script specifically for this purpose:
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
It says:
> Purpose
> The intended use of the scripts is for Continuous Integration (CI) scenarios, where:
> * The SDK needs to be installed without user interaction and without admin rights.
> * The SDK installation doesn't need to persist across multiple CI runs.

The second bullet point is our exact scenario.

**Comment by colin-anderson** [comment]
Good idea, probably worth a try! I'll leave the issue closed for now, but we can always reopen it later if/when one of us has the time and energy to work on it 😅
