### ISSUE TITLE
Add `net6.0` as a framework target

### ISSUE THREAD

**Issue by colin-anderson** [IonxSolutions/serilog-sinks-syslog#24]
#23 (Move to GitHub Actions) is a prerequisite.

1. Update csproj files for `Serilog.Sinks.Syslog` and `Serilog.Sinks.Syslog.Tests`
2. Ensure tests pass on Windows and Linux for `net6.0`
3. Update GitHub Actions as needed for .NET 6 (assuming they support it 🤞!)
4. Ensure CI works as expected

**Comment by Kevin-Andrew** [comment]
Since .NET 6 should be released in just a few months in November of 2021 and will be considered as the "Long Term Support" release, it would probably be more advantageous to change this enhancement to specify the use of .NET 6 instead of .NET 5.

I realize this was created before .NET 6 was even announced. But I just wanted to draw attention to it now and the major factor being the Long Term Support.

**Comment by alikrc** [comment]
dotnet 6 example would be appreciated

**Comment by Kevin-Andrew** [comment]
@alikrc , I'm not sure I understand your request for a .NET 6 example of `Serilog.Sinks.SyslogMessages`. The Nuget package that you end up adding is "_multi-targeted_", that is, the source code is built to target 3 different dependencies:
1. The original .NET Framework (will work with any .NET Framework project v4.6.2 and greater).
2. .NETCore version 3.1
3. .NETStandard version 2.0

The new .NET 6 is nothing more than the next version of .NETCore. Therefore, your best option is to use the .NETStandard build of the Nuget package.

The source code to use `Serilog.Sinks.SyslogMessages` is exactly the same, regardless of what underlying .NET your project is. So the example code shown in the Getting Started section of the home page of this project (https://github.com/IonxSolutions/serilog-sinks-syslog#getting-started) should work for your .NET 6 project, when you reference the .NETStandard of the Nuget package (which should happen automatically, I believe).

I will hopefully be updating my Visual Studio to 2022 and therefore have .NET 6 and can give this a try. But in the meantime, if you believe something specific isn't working with regards to using this in .NET 6, you can let us know some more details.

**Comment by alikrc** [comment]
@Kevin-Andrew tnx for your detailed and quick reply. I've tried this package with a new dotnet 6 application and tried to send logs to graylog with syslog udp input and it didn't work. So i assumed that this package may not be working. I'm fairly new to this logging thing so i might done misconfig.

**Comment by colin-anderson** [comment]
net6.0 and net7.0 are targets now, but we haven't switched to GitHub Actions yet.
