### ISSUE TITLE
Changing the appName/Identity/Tag via the LocalSyslog Sink

### ISSUE THREAD

**Issue by Sonorpearl** [IonxSolutions/serilog-sinks-syslog#3]
Hello everyone. It would be really nice if you could change the appName/Identity/Tag like in the Tcp and Udp Syslogger.  Thanks in advance.

**Comment by Sonorpearl** [comment]
#4

**Comment by colin-anderson** [comment]
@Sonorpearl hi, thanks for the idea and contribution!

At a glance your PR looks fine - I'll try to get this merged today if possible 🙏

**Comment by colin-anderson** [comment]
Thanks again, PR merged and version [1.0.4](https://www.nuget.org/packages/Serilog.Sinks.SyslogMessages/1.0.4) pushed to Nuget!
