### ISSUE TITLE
是否尝试过tcp协议 写入elk？

### ISSUE THREAD

**Issue by www5255977** [IonxSolutions/serilog-sinks-syslog#31]
我添加包引用  代码如下 
 public class Program
    {
        public static void Main(string[] args)
        {

            Log.Logger = new LoggerConfiguration()
               .MinimumLevel.Debug()
               .WriteTo.Console()
               .WriteTo.TcpSyslog(host: "172.16.146.77", port: 6040)
               //.WriteTo.TcpSyslog("172.16.146.77:6040")
               .CreateLogger();

            Log.Information(JsonConvert.SerializeObject(new { applicationName = "emr-doctor", executeResult= "doctor接诊", requestUrl = "/PublicPatient/Accepts" }));

            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }

并未写入elk

**Comment by www5255977** [comment]
We need a component that can write to Logstash over TCP .   I just saw your GitHub .  Then download the source code and try it out But there is no corresponding logstash.  The code is in the reply above

**Comment by colin-anderson** [comment]
So, there are different ways to get logs into Logstash, but you haven't provided anything from your Logstash config, so I don't know which you are using.

1. If you are using the [TCP Input Plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html), that does not ingest Syslog events - it ingests newline-delimited events over raw TCP. For this, you want [Serilog.Sinks.Network](https://github.com/pauldambra/Serilog.Sinks.Network)

2. If you are using the [Syslog Input Plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html), then it should work (I haven't specifically tested that, but Syslog is a well-defined standard)

Would appreciate if you could let me know which ingestor you are using, and if it's the Syslog Input Plugin, I need to see your Logstash configuration too please.

**Comment by colin-anderson** [comment]
Nǐhǎo!

Just wanted to check if you were still having issues, otherwise I will close this?
