### ISSUE TITLE
Customizing host name

### ISSUE THREAD

**Issue by stevebrough** [IonxSolutions/serilog-sinks-syslog#38]
The option sourceHostOverride is not available in 2.0.5 nuget package.

**Comment by colin-anderson** [comment]
We were trying to avoid doing a new release for just that one change, but I expect we'll do another release very shortly when #37 is ready for merge 👍

In the meantime, this is a simple workaround available [here](https://github.com/IonxSolutions/serilog-sinks-syslog/pull/36#issuecomment-877117643).

**Comment by stevebrough** [comment]
No sweat, I have already worked around it.
Just wanted to let you know in case it was an oversight.
Cheers

**Comment by colin-anderson** [comment]
@stevebrough just a quick note to say that v2.0.6 is released, which includes sourceHostOverride 👍
