### ISSUE TITLE
Unable to read syslog configuration in web.config 

### ISSUE THREAD

**Issue by arbtin-test** [IonxSolutions/serilog-sinks-syslog#50]
I'm using appsettings 

```
new LoggerConfiguration()
   .Enrich.FromLogContext()
   .ReadFrom.AppSettings());
```

configuration in Web.config:
```
<add key="serilog:using:tcpSyslog" value="Serilog.Sinks.Syslog" />  
<add key="serilog:write-to:tcpSyslog.Host" value="xx.xx.xx.xx" />  
<add key="serilog:write-to:tcpSyslog.Port" value="514" />  
<add key="serilog:write-to:tcpSyslog.secureProtocols" value="Tls12" />  
<add key="serilog:write-to:tcpSyslog.syslogFormat" value="RFC5424" />  
<add key="serilog:write-to:tcpSyslog.facility" value="User" />  
<add key="serilog:write-to:tcpSyslog.framingType" value="LF" />  
```

I have File and Console configurations in the .config file and these both work as expected.

**Comment by colin-anderson** [comment]
The configuration is blank, I guess something went wrong with copy-paste?

Also, if you could you please attach a minimal reproduction project, I'm sure we can figure this out for you?

**Comment by Kevin-Andrew** [comment]
@arbtin-test , I just submitted a pull request, #51 , that you can look at as an example. It extends one of the sample projects to include an `App.config` file, which should be the same for your `web.config` file needs.

The example uses the `UdpSyslog` sink, but based upon that and the information you provided, I think I see a few errors in the settings you provided.

On your first line, you need a capital `T` for `TcpSyslog`. This needs to match the class name.

Then, for the `host` and `port` parameters, they need to be all lower-case to match the parameter name of the configuration extension method:
![image](https://user-images.githubusercontent.com/22459191/158031226-fbef28a2-011e-41c7-82b7-2987a9c2702a.png)

Give those a try and see what happens.

**Comment by Kevin-Andrew** [comment]
@arbtin-test , we are going to mark this issue as closed, as we haven't heard back from you.
