### ISSUE TITLE
Exception in  EnsureConnected method in SyslogTcpSink when OS do not support IPv6

### ISSUE THREAD

**Issue by PavPav** [IonxSolutions/serilog-sinks-syslog#66]
In `SyslogTcpSink.cs` in EnsureConnected method there is a following code
`this.client = new TcpClient(Socket.OSSupportsIPv6 ? AddressFamily.InterNetworkV6 : AddressFamily.InterNetwork);
                this.client.Client.DualMode = Socket.OSSupportsIPv6;`
Setting `DualMode` to false (OS do not support IPv6) will throw `[NotSupportedException]`  [(doc)](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.dualmode?view=net-7.0)
`DualMode` setter looks like this:

```
set
{
  if (this.AddressFamily != AddressFamily.InterNetworkV6)
    throw new NotSupportedException(SR.GetString("net_invalidversion"));
  this.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, value ? 0 : 1);
}

```
Seems that the fix might be not setting this flag at all if IPv6 not supported

**Comment by colin-anderson** [comment]
Heh, that is quite a coincidence 😃 

Resolved by #65, with the fix available in [v3.0.1](https://www.nuget.org/packages/Serilog.Sinks.SyslogMessages/3.0.1)
